### ISSUE TITLE
mp4-hls.py: ERROR: failed to write samples (-23)

### ISSUE THREAD

**Issue by haridarshan** [axiomatic-systems/Bento4#360]
Hi @barbibulle 

As mentioned in issue no #133, am also getting same error when doing hls segmentation. Here is the command and verbose debug info 

```
/opt/bento4/bin/mp4hls -v -d -f -o fhd_265_23/hls --audio-format=ts --segment-duration=6 --master-playlist-name=fhd_265_23.m3u8 --media-playlist-name=chunk.m3u8 fhd_265_23.mp4
```
Here is the entire trace and debug info with verbose

> Parsing media file fhd_265_23.mp4
> Processing MP4 file fhd_265_23.mp4
>   found 6 segments
> COMMAND:  /opt/bento4/utils/../bin/mp4info --fast --format json fhd_265_23.mp4 ['/opt/bento4/utils/../bin/mp4info', '--fast', '--format', 'json', 'fhd_265_23.mp4']
> COMMAND:  /opt/bento4/utils/../bin/mp4dump --verbosity 1 --format json fhd_265_23.mp4 ['/opt/bento4/utils/../bin/mp4dump', '--verbosity', '1', '--format', 'json', 'fhd_265_23.mp4']
> Track ID                     = 1
>     Segment Count            = 2
>     Type                     = video
>     Sample Count             = 1499
>     Average segment bitrate  = 29186982
>     Max segment bitrate      = 27063578
>     Required bandwidth       = 27063578
>     Average segment duration = 30.76
> Track ID                     = 2
>     Segment Count            = 3
>     Type                     = audio
>     Sample Count             = 2813
>     Average segment bitrate  = 141185
>     Max segment bitrate      = 141195
>     Required bandwidth       = 141178
>     Average segment duration = 30.7626666667
> Track ID                     = 3
>     Segment Count            = 1
>     Type                     = other
>     Sample Count             = 1
>     Average segment bitrate  = 14
>     Max segment bitrate      = 14
>     Required bandwidth       = 14
>     Average segment duration = 59.96
> Processing fhd_265_23.mp4
> COMMAND:  /opt/bento4/utils/../bin/mp42hls --hls-version 4 --iframe-index-filename fhd_265_23/hls/media-1/iframes.m3u8 --show-info --segment-url-template segment-%d.ts --segment-filename-template fhd_265_23/hls/media-1/segment-%d.ts --segment-duration 6 --index-filename fhd_265_23/hls/media-1/chunk.m3u8 --encryption-key-uri key.bin fhd_265_23.mp4 ['/opt/bento4/utils/../bin/mp42hls', '--hls-version', '4', '--iframe-index-filename', 'fhd_265_23/hls/media-1/iframes.m3u8', '--show-info', '--segment-url-template', 'segment-%d.ts', '--segment-filename-template', 'fhd_265_23/hls/media-1/segment-%d.ts', '--segment-duration', '6', '--index-filename', 'fhd_265_23/hls/media-1/chunk.m3u8', '--encryption-key-uri', 'key.bin', 'fhd_265_23.mp4']
> ERROR: failed to write samples (-23)
> Traceback (most recent call last):
>   File "/opt/bento4/bin/../utils/mp4-hls.py", line 652, in <module>
>     main()
>   File "/opt/bento4/bin/../utils/mp4-hls.py", line 642, in main
>     OutputHls(options, media_sources)
>   File "/opt/bento4/bin/../utils/mp4-hls.py", line 307, in OutputHls
>     ProcessSource(options, media_info, out_dir)
>   File "/opt/bento4/bin/../utils/mp4-hls.py", line 234, in ProcessSource
>     **kwargs)
>   File "/opt/bento4/utils/mp4utils.py", line 303, in Mp42Hls
>     return Bento4Command(options, 'mp42hls', input_filename, *args, **kwargs)
>   File "/opt/bento4/utils/mp4utils.py", line 282, in Bento4Command
>     raise Exception(message)
> Exception: binary tool failed with error 1 - ['/opt/bento4/utils/../bin/mp42hls', '--hls-version', '4', '--iframe-index-filename', 'fhd_265_23/hls/media-1/iframes.m3u8', '--show-info', '--segment-url-template', 'segment-%d.ts', '--segment-filename-template', 'fhd_265_23/hls/media-1/segment-%d.ts', '--segment-duration', '6', '--index-filename', 'fhd_265_23/hls/media-1/chunk.m3u8', '--encryption-key-uri', 'key.bin', 'fhd_265_23.mp4']

Also, is it possible to use skm with hls like we use in-case of mp4dash?? and how can we pass segment-duration in-case of mp4dash

**Comment by jonathanulco** [comment]
Hi @haridarshan i've the same issue. Maybe you've solved this ? And how ?

**Comment by haridarshan** [comment]
@jonathanulco 
Issue wasn't resolved for mp42hls, so, I've written custom python script integrated with mp4-dash.py and solved it. Now I'm able to do dash and hls segmentation through mp4dash command only

If required I can share the custom script and parser options added to mp4dash to make it working

**Comment by DamianImrich** [comment]
For me refragmenting problematic video with **ffmpeg -movflags faststart** fixed issue.

`ffmpeg -i 1080p_mp4fragment.mp4 -c copy -movflags faststart 1080p_ffmpegfragment.mp4`

Here is full explanation of problem #133.
