### ISSUE TITLE
mp4hls: Expecting , delimiter

### ISSUE THREAD

**Issue by everythingspirals** [axiomatic-systems/Bento4#471]
When I use `mp4hls` I get the following error
`ERROR: Expecting , delimiter: line 8 column 21 (char 231)`

Here is `mp4info` output of my file
```File:
  major brand:      isom
  minor version:    200
  compatible brand: isom
  compatible brand: iso2
  compatible brand: avc1
  compatible brand: iso6
  compatible brand: mp41
  compatible brand: iso5
  fast start:       yes

Movie:
  duration:   0 ms
  time scale: 1000
  fragments:  yes

Found 2 Tracks
Track 1:
  flags:        7 ENABLED IN-MOVIE IN-PREVIEW
  id:           1
  type:         Video
  duration: 0 ms
  language: und
  media:
    sample count: 0
    timescale:    12288
    duration:     0 (media timescale units)
    duration:     0 (ms)
    bitrate (computed): 153.490 Kbps
    sample count with fragments: 366
    duration with fragments:     187392
    duration with fragments:     15250 (ms)
  display width:  192.000000
  display height: 108.000000
  Sample Description 0
    Coding:      avc1 (H.264)
    Width:       192
    Height:      108
    Depth:       24
    AVC Profile:          77 (Main)
    AVC Profile Compat:   40
    AVC Level:            11
    AVC NALU Length Size: 4
    AVC SPS: [674d400beca187fde022000003000200000300601e28532c]
    AVC PPS: [68efbc80]
    Codecs String: avc1.4D400B
Track 2:
  flags:        7 ENABLED IN-MOVIE IN-PREVIEW
  id:           2
  type:         Audio
  duration: 0 ms
  language: und
  media:
    sample count: 0
    timescale:    44100
    duration:     0 (media timescale units)
    duration:     0 (ms)
    bitrate (computed): 28.877 Kbps
    sample count with fragments: 589
    duration with fragments:     672347
    duration with fragments:     15246 (ms)
  Sample Description 0
    Coding:      mp4a (MPEG-4 Audio)
    Stream Type: Audio
    Object Type: MPEG-4 Audio
    Max Bitrate: 32000
    Avg Bitrate: 0
    Buffer Size: 0
    Codecs String: mp4a.40.2
    MPEG-4 Audio Object Type: 2 (AAC Low Complexity)
    MPEG-4 Audio Decoder Config:
      Sampling Frequency: 44100
      Channels: 1
      Extension:
        Object Type: Spectral Band Replication
        SBR Present: no
        PS Present:  no
        Sampling Frequency: 0
    Sample Rate: 44100
    Sample Size: 16
    Channels:    2```

**Comment by barbibulle** [comment]
Could you re-run the `mp4info` command with the `--format json` option and copy the output? Thanks.

**Comment by everythingspirals** [comment]
```
stdout: {
"file":{
  "major_brand":"isom",
  "minor_version":512,
  "compatible_brands":["isom", "iso2", "avc1", "iso6", "mp41", "iso5"],
  "fast_start":true
},
"movie":{
  "duration_ms":0,
  "duration":0,
  "time_scale":1000,
  "fragments":true
},
"tracks":[
{
  "flags":7,
  "flag_names":["ENABLED" ,"IN-MOVIE" ,"IN-PREVIEW"],
  "id":1,
  "type":"Video",
  "duration_ms":0,
  "language":"und",
  "media":{
    "sample_count":0,
    "timescale":12288,
    "duration":0,
    "duration_ms":0,
    "bitrate":153.600,
    "sample_count_with_fragments":366,
    "duration_with_fragments":187392,
    "duration_with_fragments_ms":15250
  },
  "display_width":192.000000,
  "display_height":108.000000,
  "sample_descriptions":[
{
"coding":"avc1",
"coding_name":"H.264",
"width":192,
"height":108,
"depth":24,
"avc_profile":77,
"avc_profile_name":"Main",
"avc_profile_compat":64,
"avc_level":11,
"avc_nalu_length_size":4,
"avc_sps": ["674d400beca187fde022000003000200000300601e28532c"],
"avc_pps": ["68efbc80"],
"codecs_string":"avc1.4D400B"
}  ]
},
{
  "flags":7,
  "flag_names":["ENABLED" ,"IN-MOVIE" ,"IN-PREVIEW"],
  "id":2,
  "type":"Audio",
  "duration_ms":0,
  "language":"und",
  "media":{
    "sample_count":0,
    "timescale":44100,
    "duration":0,
    "duration_ms":0,
    "bitrate":28.877,
    "sample_count_with_fragments":589,
    "duration_with_fragments":672347,
    "duration_with_fragments_ms":15246
  },
  "sample_descriptions":[
{
"coding":"mp4a",
"coding_name":"MPEG-4 Audio",
"stream_type":5,
"stream_type_name":"Audio",
"object_type":64,
"object_type_name":"MPEG-4 Audio",
"max_bitrate":32000,
"average_bitrate":0,
"buffer_size":0,
"decoder_info": "120856e500",
"codecs_string": "mp4a.40.2",
"mpeg_4_audio_object_type":2,
"mpeg_4_audio_object_type_name":"AAC Low Complexity",
"mpeg_4_audio_decoder_config":{
  "sampling_frequency":44100,
  "channels":1
,
  "extension":{
    "object_type":5,
    "object_type_name":"Spectral Band Replication",
    "sbr_present":false,
    "ps_present":false,
    "sampling_frequency":0
  }
},
"sample_rate":44100,
"sample_size":16,
"channels":2
}  ]
}]
}
```

**Comment by barbibulle** [comment]
That looks fine. Could you try re-running `mp4hls` with the `--debug --verbose` options? to see where the error occurs (I was assuming an issue with the JSON output of `mp4info` but that may not be the case)

**Comment by everythingspirals** [comment]
```
Processing C:\Users\Dushan\Code\api\transcoder\transcodes\5e39f29219910b6c84ea24b6/192.mp4
COMMAND:  C:\Users\Dushan\Desktop\bento4\utils\..\bin\mp42hls --hls-version 4 --iframe-index-filename output\media-1\iframes.m3u8 --show-info --segment-url-template segment-%d.ts --segment-filename-template output\media-1\segment-%d.ts --index-filename output\media-1\stream.m3u8 --encryption-key-uri key.bin C:\Users\Dushan\Code\api\transcoder\transcodes\5e39f29219910b6c84ea24b6/192.mp4 ['C:\\Users\\Dushan\\Desktop\\bento4\\utils\\..\\bin\\mp42hls', '--hls-version', '4', '--iframe-index-filename', 'output\\media-1\\iframes.m3u8', '--show-info', '--segment-url-template', 'segment-%d.ts', '--segment-filename-template', 'output\\media-1\\segment-%d.ts', '--index-filename', 'output\\media-1\\stream.m3u8', '--encryption-key-uri', 'key.bin', 'C:\\Users\\Dushan\\Code\\api\\transcoder\\transcodes\\5e39f29219910b6c84ea24b6/192.mp4']

stderr: Traceback (most recent call last):
  File "C:\Users\Dushan\Desktop\bento4\bin\..\utils\mp4-hls.py", line 652, in <module>
    main()
  File "C:\Users\Dushan\Desktop\bento4\bin\..\utils\mp4-hls.py", line 642, in main
    OutputHls(options, media_sources)
  File "C:\Users\Dushan\Desktop\bento4\bin\..\utils\mp4-hls.py", line 307, in OutputHls
    ProcessSource(options, media_info, out_dir)
  File "C:\Users\Dushan\Desktop\bento4\bin\..\utils\mp4-hls.py", line 236, in ProcessSource
    media_info['info'] = json.loads(json_info, strict=False)
  File "C:\Python27\lib\json\__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 8 column 21 (char 231)
```

**Comment by everythingspirals** [comment]
```
Processing transcoder\transcodes\5e39f29219910b6c84ea24b6/192.mp4
COMMAND: bento4\utils\..\bin\mp42hls --hls-version 4 --iframe-index-filename output\media-1\iframes.m3u8 --show-info --segment-url-template segment-%d.ts --segment-filename-template output\media-1\segment-%d.ts --index-filename output\media-1\stream.m3u8 --encryption-key-uri key.bin C:\Users\User\Code\api\transcoder\transcodes\5e39f29219910b6c84ea24b6/192.mp4 ['C:\\Users\\User\\Desktop\\bento4\\utils\\..\\bin\\mp42hls', '--hls-version', '4', '--iframe-index-filename', 'output\\media-1\\iframes.m3u8', '--show-info', '--segment-url-template', 'segment-%d.ts', '--segment-filename-template', 'output\\media-1\\segment-%d.ts', '--index-filename', 'output\\media-1\\stream.m3u8', '--encryption-key-uri', 'key.bin', 'C:\\Users\\User\\Code\\api\\transcoder\\transcodes\\5e39f29219910b6c84ea24b6/192.mp4']

stderr: Traceback (most recent call last):
  File "bento4\bin\..\utils\mp4-hls.py", line 652, in <module>
    main()
  File bento4\bin\..\utils\mp4-hls.py", line 642, in main
    OutputHls(options, media_sources)
  File "bento4\bin\..\utils\mp4-hls.py", line 307, in OutputHls
    ProcessSource(options, media_info, out_dir)
  File "bento4\bin\..\utils\mp4-hls.py", line 236, in ProcessSource
    media_info['info'] = json.loads(json_info, strict=False)
  File "C:\Python27\lib\json\__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 8 column 21 (char 231)
```

**Comment by everythingspirals** [comment]
Seems like it's happening here 

`mp4-hls.py`

```
    print json_info
    media_info['info'] = json.loads(json_info, strict=False)
```

`json_info`
```
{
  "stats": {
    "duration": 0.000000,
    "avg_segment_bitrate": 240903.715068,
    "max_segment_bitrate": 270016.831169,
    "avg_iframe_bitrate": 7812.558904,
    "max_iframe_bitrate": 13594.597403,
    "frame_rate": -1.#IND00
  },
  "audio": {
    "codec": "mp4a.40.2"
  },
  "video": {
    "codec": "avc1.4D400B",
    "width": 192,
    "height": 108
  }
}
```

`frame_rate` seems misformed
`"frame_rate": -1.#IND00`

**Comment by barbibulle** [comment]
Ok, got it. That's a bug that sneaked in in the last update. I will push out a fix for it and update the binary releases.

**Comment by everythingspirals** [comment]
Cool, thanks
