### ISSUE TITLE
ERROR: 'width' when running mp4dash

### ISSUE THREAD

**Issue by dominic-p** [axiomatic-systems/Bento4#499]
I'm getting a strange error when I attempt to dash an MP4 file. I encoded it with ffmpeg and then fragmented it with `mp4fragment big-buck-bunny-av1-512.mp4 big-buck-bunny-av1-512-frag.mp4` which gave the output:
> found regular I-frame interval: 73 frames (at 24.000 frames per second)

But, when I try to dash the file I get an error:
```
mp4dash big-buck-bunny-av1-512-frag.mp4
Parsing media file 1: big-buck-bunny-av1-512-frag.mp4
ERROR: 'width'
```

This happens with several other files as well. I ran into it on Windows and an Ubuntu 18 virtual machine both running Version 2.0.0 r634.

Any idea where this error is coming from and how I can work around it?

**Comment by barbibulle** [comment]
Could you re-run the same command with the `-d` command line parameter, so capture the stack trace when the error occurs? Or if you could send a link to the file you're getting the error with, I can try to reproduce the issue locally.

**Comment by dominic-p** [comment]
Thanks for the response. Here's the output with the -d flag:

```
mp4dash -f -d big-buck-bunny-av1-512-frag.mp4
COMMAND:  C:\\bin\bento4\utils\..\bin\mp4info --format json --fast big-buck-bunny-av1-512-frag.mp4 ['C:\\bin\\bento4\\utils\\..\\bin\\mp4info', '--format', 'json', '--fast', 'big-buck-bunny-av1-512-frag.mp4']
Parsing media file 1: big-buck-bunny-av1-512-frag.mp4
Processing MP4 file big-buck-bunny-av1-512-frag.mp4
  found 209 segments
Traceback (most recent call last):
  File "C:\\bin\bento4\bin\..\utils\mp4-dash.py", line 2049, in <module>
    main()
  File "C:\\bin\bento4\bin\..\utils\mp4-dash.py", line 1839, in main
    (audio_sets, video_sets, subtitles_sets, mp4_files) = SelectTracks(options, media_sources)
  File "C:\\bin\bento4\bin\..\utils\mp4-dash.py", line 1213, in SelectTracks
    mp4_file = Mp4File(options, media_source)
  File "C:\\bin\bento4\utils\mp4utils.py", line 523, in __init__
    self.tracks[track['id']] = Mp4Track(self, track)
  File "C:\\bin\bento4\utils\mp4utils.py", line 406, in __init__
    self.width  = sample_desc['width']
KeyError: 'width'
```

I have also noticed that this only happens on AV1 encoded files. I'm able to dash H.264 and HEVC files no problem. Maybe there's some compatibility issue with AV1 video?

Here is the file that I'm attempting to dash (this is after I ran mp4fragment on it): https://filebin.net/cibu35zepvikp1le/big-buck-bunny-av1-512-frag.mp4?t=1f85riu7

**Comment by dominic-p** [comment]
I just saw #393. That's probably what's going on here.

**Comment by gregoriopellegrino** [comment]
Same error here, on mac.

**Comment by barbibulle** [comment]
@dominic-p Could you re-post the example file? the link you posted here doesn't work

**Comment by dominic-p** [comment]
Sorry for the delay on this. Here is the file again: https://gofile.io/d/mc7r92

**Comment by jgill-QA** [comment]
Hi, @barbibulle and @dominic-p 

I am working on generating some DRM encrypted test content.   

Encrypting track IDs [1] in \Documents\DRMcontentGeneration\p3254.mp4
Parsing media file 1: tmpo4x0gxpg = Encrypted[\Documents\DRMcontentGeneration\p3254.mp4]
ERROR: 'width'

Do you know why this error might occur.

**Comment by barbibulle** [comment]
Hi. Can you confirm you're using the latest version of the tool? If so, would it be possible to share the file with which you're having the issue so that I can try to replicate the problem on my side?

**Comment by dominic-p** [comment]
I'm sorry @jgill-QA I've had to step away from my video encoding projects for the time being, so I can't be of much help here.
