### ISSUE TITLE
mp4dump outputs illegal json string

### ISSUE THREAD

**Issue by willkk** [axiomatic-systems/Bento4#505]
This file has a meta item ©cmt, whose value is `{"source":"m2u"}`. The output json is 
```
...
1484         {
1485           "name":".cmt",
1486           "header_size":8,
1487           "size":40,
1488           "children":[
1489           {
1490             "name":"data",
1491             "header_size":8,
1492             "size":32,
1493             "type":1,
1494             "lang":0,
1495             "value":"{"source":"m2u"}"
1496           }]
1497         },
...
```
![image](https://user-images.githubusercontent.com/17777977/81690008-5ffdf580-948d-11ea-823c-6cb3d9f0ffca.png)

And the following command failed:
```
/usr/local/services/bento4-1.0/bin/mp4hls --hls-version=3 --audio-format=ts --master-playlist-name=adp.10.m3u8 --media-playlist-name=media.m3u8 file1.mp4 file2.mp4 file3.mp4 -o output
Traceback (most recent call last):
  File "/usr/local/services/bento4-1.0/bin/../utils/mp4-hls.py", line 657, in <module>
    main()
  File "/usr/local/services/bento4-1.0/bin/../utils/mp4-hls.py", line 647, in main
    OutputHls(options, media_sources)
  File "/usr/local/services/bento4-1.0/bin/../utils/mp4-hls.py", line 254, in OutputHls
    AnalyzeSources(options, media_sources)
  File "/usr/local/services/bento4-1.0/bin/../utils/mp4-hls.py", line 102, in AnalyzeSources
    mp4_file = Mp4File(Options, media_source)
  File "/usr/local/services/bento4-1.0/utils/mp4utils.py", line 520, in __init__
    self.tree = json.loads(json_dump, strict=False, object_pairs_hook=collections.OrderedDict)
  File "/usr/local/services/python/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/local/services/python/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/services/python/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 1495 column 24 (char 65194)
```

**Comment by willkk** [comment]
Which file should I update in the release pkg?

**Comment by willkk** [comment]
I have build newest bin files from master branch. And it is fixed. 👍 !
