### ISSUE TITLE
mp4dump doesn't support unicode

### ISSUE THREAD

**Issue by willkk** [axiomatic-systems/Bento4#512]
I build mp4dump myself from master branch code. The relative issue is [issue 505](https://github.com/axiomatic-systems/Bento4/issues/505). It seems that this fix introduces a new bug here. As far as I know, the old version mpd4dump works.

user data in mp4:
```
113136        {
113137           "name":".nam",
113138           "header_size":8,
113139           "size":49,
113140           "children":[
113141           {
113142             "name":"data",
113143             "header_size":8,
113144             "size":41,
113145             "type":1,
113146             "lang":0,
113147             "value":"EV\u00 5\u00 D\u00 5\u00 5\u00 1\u00 F3.9.7\u00 8\u00 D\u00 F\u00 4\u00 B\u00 6\u00 5\u00 D\u00 5\u00 5\u00 8\u00 6"
113148           }]
113149         },
```

cmd:
```
/usr/local/services/bento4-1.0/bin/mp4hls --hls-version=3 --audio-format=ts --master-playlist-name=adp.10.m3u8 --media-playlist-name=media.m3u8 f0.mp4 f1.mp4 f2.mp4 -o output -d
```

traceback:
```
Traceback (most recent call last):
  File "/usr/local/services/bento4-1.0/bin/../utils/mp4-hls.py", line 657, in <module>
    main()
  File "/usr/local/services/bento4-1.0/bin/../utils/mp4-hls.py", line 647, in main
    OutputHls(options, media_sources)
  File "/usr/local/services/bento4-1.0/bin/../utils/mp4-hls.py", line 254, in OutputHls
    AnalyzeSources(options, media_sources)
  File "/usr/local/services/bento4-1.0/bin/../utils/mp4-hls.py", line 102, in AnalyzeSources
    mp4_file = Mp4File(Options, media_source)
  File "/usr/local/services/bento4-1.0/utils/mp4utils.py", line 520, in __init__
    self.tree = json.loads(json_dump, strict=False, object_pairs_hook=collections.OrderedDict)
  File "/usr/local/services/python/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/local/services/python/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/services/python/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid \uXXXX escape: line 113147 column 25 (char 6051478)
```

**Comment by barbibulle** [comment]
Yes, sorry, I definitely messed this up. I'll have a fix shortly.

**Comment by barbibulle** [comment]
Should be fixed in master now

**Comment by willkk** [comment]
Nice work! 👍

**Comment by willkk** [comment]
Has this issue been fixed yet?

**Comment by willkk** [comment]
@barbibulle Hi barbibulle， is this issue fixed now?

**Comment by barbibulle** [comment]
Yes. The fix is merged in master and the pre-compiled binaries have been updated. Let me know if something's not working as expected.

**Comment by willkk** [comment]
Great work! 👍
