### ISSUE TITLE
Out-of-Memory with ASAN in mp4split

### ISSUE THREAD

**Issue by Yhcrown** [axiomatic-systems/Bento4#737]
Hi, developers of Bento4:

I found a strange error when I was testing mp4split: For some of my input, the program will get stuck and can only be ended by Ctrl+C. For my crash input, program will get stuck for a while and then killed by OS. Then when I run the program again with the same crash input, it may incur a error, information is here: (I'm sorry that now I can't reproduce  this error steadily)

```
=================================================================
==79908==ERROR: AddressSanitizer: allocator is out of memory trying to allocate 0xfb00000a0 bytes
    #0 0x55d5bdbfc83d in operator new(unsigned long) (/workspace/test/Bento4/check_build/mp4split+0x11f83d) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
    #1 0x55d5bdcbc90d in AP4_TrunAtom::AP4_TrunAtom(unsigned int, unsigned char, unsigned int, AP4_ByteStream&) (/workspace/test/Bento4/check_build/mp4split+0x1df90d) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
    #2 0x55d5bdcbc33b in AP4_TrunAtom::Create(unsigned int, AP4_ByteStream&) (/workspace/test/Bento4/check_build/mp4split+0x1df33b) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
    #3 0x55d5bdc0fc52 in AP4_AtomFactory::CreateAtomFromStream(AP4_ByteStream&, unsigned int, unsigned int, unsigned long long, AP4_Atom*&) (/workspace/test/Bento4/check_build/mp4split+0x132c52) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
    #4 0x55d5bdc0ec6a in AP4_AtomFactory::CreateAtomFromStream(AP4_ByteStream&, unsigned long long&, AP4_Atom*&) (/workspace/test/Bento4/check_build/mp4split+0x131c6a) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
    #5 0x55d5bdc1fef0 in AP4_ContainerAtom::ReadChildren(AP4_AtomFactory&, AP4_ByteStream&, unsigned long long) (/workspace/test/Bento4/check_build/mp4split+0x142ef0) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
    #6 0x55d5bdc1f214 in AP4_ContainerAtom::Create(unsigned int, unsigned long long, bool, bool, AP4_ByteStream&, AP4_AtomFactory&) (/workspace/test/Bento4/check_build/mp4split+0x142214) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
    #7 0x55d5bdc1041d in AP4_AtomFactory::CreateAtomFromStream(AP4_ByteStream&, unsigned int, unsigned int, unsigned long long, AP4_Atom*&) (/workspace/test/Bento4/check_build/mp4split+0x13341d) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
    #8 0x55d5bdc0ec6a in AP4_AtomFactory::CreateAtomFromStream(AP4_ByteStream&, unsigned long long&, AP4_Atom*&) (/workspace/test/Bento4/check_build/mp4split+0x131c6a) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
    #9 0x55d5bdc1fef0 in AP4_ContainerAtom::ReadChildren(AP4_AtomFactory&, AP4_ByteStream&, unsigned long long) (/workspace/test/Bento4/check_build/mp4split+0x142ef0) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
    #10 0x55d5bdc1f214 in AP4_ContainerAtom::Create(unsigned int, unsigned long long, bool, bool, AP4_ByteStream&, AP4_AtomFactory&) (/workspace/test/Bento4/check_build/mp4split+0x142214) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
    #11 0x55d5bdc1041d in AP4_AtomFactory::CreateAtomFromStream(AP4_ByteStream&, unsigned int, unsigned int, unsigned long long, AP4_Atom*&) (/workspace/test/Bento4/check_build/mp4split+0x13341d) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
    #12 0x55d5bdc0ec6a in AP4_AtomFactory::CreateAtomFromStream(AP4_ByteStream&, unsigned long long&, AP4_Atom*&) (/workspace/test/Bento4/check_build/mp4split+0x131c6a) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
    #13 0x55d5bdc393d6 in AP4_DrefAtom::AP4_DrefAtom(unsigned int, unsigned char, unsigned int, AP4_ByteStream&, AP4_AtomFactory&) (/workspace/test/Bento4/check_build/mp4split+0x15c3d6) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
    #14 0x55d5bdc38e1b in AP4_DrefAtom::Create(unsigned int, AP4_ByteStream&, AP4_AtomFactory&) (/workspace/test/Bento4/check_build/mp4split+0x15be1b) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
    #15 0x55d5bdc10dfc in AP4_AtomFactory::CreateAtomFromStream(AP4_ByteStream&, unsigned int, unsigned int, unsigned long long, AP4_Atom*&) (/workspace/test/Bento4/check_build/mp4split+0x133dfc) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
    #16 0x55d5bdc0ec6a in AP4_AtomFactory::CreateAtomFromStream(AP4_ByteStream&, unsigned long long&, AP4_Atom*&) (/workspace/test/Bento4/check_build/mp4split+0x131c6a) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
    #17 0x55d5bdc1fd22 in AP4_ContainerAtom::ReadChildren(AP4_AtomFactory&, AP4_ByteStream&, unsigned long long) (/workspace/test/Bento4/check_build/mp4split+0x142d22) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
    #18 0x55d5bdc1f214 in AP4_ContainerAtom::Create(unsigned int, unsigned long long, bool, bool, AP4_ByteStream&, AP4_AtomFactory&) (/workspace/test/Bento4/check_build/mp4split+0x142214) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
    #19 0x55d5bdc1041d in AP4_AtomFactory::CreateAtomFromStream(AP4_ByteStream&, unsigned int, unsigned int, unsigned long long, AP4_Atom*&) (/workspace/test/Bento4/check_build/mp4split+0x13341d) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
    #20 0x55d5bdc0ec6a in AP4_AtomFactory::CreateAtomFromStream(AP4_ByteStream&, unsigned long long&, AP4_Atom*&) (/workspace/test/Bento4/check_build/mp4split+0x131c6a) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
    #21 0x55d5bdc1fef0 in AP4_ContainerAtom::ReadChildren(AP4_AtomFactory&, AP4_ByteStream&, unsigned long long) (/workspace/test/Bento4/check_build/mp4split+0x142ef0) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
    #22 0x55d5bdc1f214 in AP4_ContainerAtom::Create(unsigned int, unsigned long long, bool, bool, AP4_ByteStream&, AP4_AtomFactory&) (/workspace/test/Bento4/check_build/mp4split+0x142214) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
    #23 0x55d5bdc1041d in AP4_AtomFactory::CreateAtomFromStream(AP4_ByteStream&, unsigned int, unsigned int, unsigned long long, AP4_Atom*&) (/workspace/test/Bento4/check_build/mp4split+0x13341d) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
    #24 0x55d5bdc0ec6a in AP4_AtomFactory::CreateAtomFromStream(AP4_ByteStream&, unsigned long long&, AP4_Atom*&) (/workspace/test/Bento4/check_build/mp4split+0x131c6a) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
    #25 0x55d5bdc1fef0 in AP4_ContainerAtom::ReadChildren(AP4_AtomFactory&, AP4_ByteStream&, unsigned long long) (/workspace/test/Bento4/check_build/mp4split+0x142ef0) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
    #26 0x55d5bdc1f214 in AP4_ContainerAtom::Create(unsigned int, unsigned long long, bool, bool, AP4_ByteStream&, AP4_AtomFactory&) (/workspace/test/Bento4/check_build/mp4split+0x142214) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
    #27 0x55d5bdc1041d in AP4_AtomFactory::CreateAtomFromStream(AP4_ByteStream&, unsigned int, unsigned int, unsigned long long, AP4_Atom*&) (/workspace/test/Bento4/check_build/mp4split+0x13341d) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
    #28 0x55d5bdc0ec6a in AP4_AtomFactory::CreateAtomFromStream(AP4_ByteStream&, unsigned long long&, AP4_Atom*&) (/workspace/test/Bento4/check_build/mp4split+0x131c6a) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
    #29 0x55d5bdc1fef0 in AP4_ContainerAtom::ReadChildren(AP4_AtomFactory&, AP4_ByteStream&, unsigned long long) (/workspace/test/Bento4/check_build/mp4split+0x142ef0) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)

==79908==HINT: if you don't care about these errors you may set allocator_may_return_null=1
SUMMARY: AddressSanitizer: out-of-memory (/workspace/test/Bento4/check_build/mp4split+0x11f83d) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f) in operator new(unsigned long)
==79908==ABORTING
```
### Crash input:
https://github.com/Yhcrown/fuzzing-crashes/blob/main/validated/mp4split/1

### hang input:
https://github.com/Yhcrown/fuzzing-crashes/blob/main/validated/mp4split/0
### Verification steps：

```
git clone https://github.com/axiomatic-systems/Bento4
cd Bento4/
mkdir check_build && cd check_build
cmake ../ -DCMAKE_C_COMPILER=clang  -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_FLAGS="-fsanitize=address" -DCMAKE_CXX_FLAGS="-fsanitize=address" -DCMAKE_BUILD_TYPE=Release
make -j 
./mp4split ./crash_input
```
enviroment:
Ubuntu 22.04 LTS
Linux lab-pro 4.15.0-147-generic
gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Ubuntu clang version 14.0.6

**Thanks & Best regards !**

**Comment by Yhcrown** [comment]
By the way, If you specify input as a directory on the command line, it will cause memory leak:
`./mp4split /workspace     ` 

```                                 
no movie found in file

=================================================================
==33904==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 72 byte(s) in 1 object(s) allocated from:
    #0 0x55e2ad12683d in operator new(unsigned long) (/workspace/test/Bento4/check_build/mp4split+0x11f83d) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
    #1 0x55e2ad12947a in main (/workspace/test/Bento4/check_build/mp4split+0x12247a) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
    #2 0x7f157c788d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 89c3cb85f9e55046776471fed05ec441581d1969)

Direct leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x55e2ad12683d in operator new(unsigned long) (/workspace/test/Bento4/check_build/mp4split+0x11f83d) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
    #1 0x55e2ad20e99d in AP4_StdcFileByteStream::Create(AP4_FileByteStream*, char const*, AP4_FileByteStream::Mode, AP4_ByteStream*&) (/workspace/test/Bento4/check_build/mp4split+0x20799d) (BuildId: 8923b6b39aee6947dbdc279d5b8a7957b217196f)
SUMMARY: AddressSanitizer: 120 byte(s) leaked in 2 allocation(s).
```

I don't know if this error is worth submitting another issue. In my opinion, this is not a big problem.
