### ISSUE TITLE
New Install of Bento has mp4hls and mp4dash errors

### ISSUE THREAD

**Issue by kirkd7** [axiomatic-systems/Bento4#903]
I setup Bento and Python v27 and both are in the path, when I try to use mp4hls I get this error:

C:\>mp4hls
Traceback (most recent call last):
  File "C:\Bento\bin\..\utils\mp4-hls.py", line 22, in <module>
    from subtitles import SubtitlesFile
  File "C:\Bento\utils\subtitles.py", line 6, in <module>
    from mp4utils import LanguageCodeMap, LanguageNames, BooleanFromString
  File "C:\Bento\utils\mp4utils.py", line 51
SyntaxError: Non-ASCII character '\xd0' in file C:\Bento\utils\mp4utils.py on line 51, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

I also tried mp4dash and also have an error related to audio:

Command (left off file list):
mp4dash --hls --no-split --use-segment-list

Error:
File "C:\Bento\bin\..\utils\mp4-dash.py", line 881
    audio_track.hls_group = f'audio/{index}' if len(ungrouped_audio_tracks) > 1 else 'audio'
                                           ^
SyntaxError: invalid syntax

Kirk

**Comment by kirkd7** [comment]
I installed on a second computer to see if the computer was an issue but still had the same issue.

However mp42hls works, but I need to create the master playlist.

**Comment by kirkd7** [comment]
I resolved the issue, it was the list of language codes in mp4utils.py, I removed all but English and now all is working.
