### ISSUE TITLE
sample_rate Error?

### ISSUE THREAD

**Issue by tekuonline** [axiomatic-systems/Bento4#99]
I used mp4fragment to generate .mp4 files from .ismv and when i try to use mp4dash, it gives me an error ```Parsing media file 1: AsterixAndObelix1080-E_230-fragmented.mp4
Processing MP4 file AsterixAndObelix1080-E_230-fragmented.mp4
  found 216292 segments
COMMAND:  ['/Applications/XAMPP/xamppfiles/htdocs/video/bento/utils/../bin/mp4info', '--fast', '--format', 'json', 'AsterixAndObelix1080-E_230-fragmented.mp4']
Traceback (most recent call last):
  File "./../utils/mp4-dash.py", line 1655, in <module>
    main()
  File "./../utils/mp4-dash.py", line 1424, in main
    (audio_sets, video_sets, subtitles_sets, mp4_files) = SelectTracks(options, media_sources)
  File "./../utils/mp4-dash.py", line 878, in SelectTracks
    mp4_file = Mp4File(Options, media_source)
  File "/Applications/XAMPP/xamppfiles/htdocs/video/bento/utils/mp4utils.py", line 502, in __init__
    self.tracks[track['id']] = Mp4Track(self, track)
  File "/Applications/XAMPP/xamppfiles/htdocs/video/bento/utils/mp4utils.py", line 410, in __init__
    self.sample_rate = sample_desc['sample_rate']
KeyError: 'sample_rate'```
Any suggestions?

**Comment by barbibulle** [comment]
Hi Tek,

I will look into this and followup shortly.

**Comment by tekuonline** [comment]
@barbibulle Any help would be appreciated.
